version: "3.8"

services:
  app:
    build: .
    environment:
      - DEBUG=true
    container_name: receipt-processor
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]